version: "3.8"

services:
  postgres:
    image: postgres:12.3
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    stdin_open: true
    tty: true
    volumes:
      - ./data:/var/lib/postgresql/data